2021-07-23 16:26:18,267 INFO    MainThread:24995 [internal.py:wandb_internal():91] W&B internal server running at pid: 24995, started at: 2021-07-23 16:26:18.267665
2021-07-23 16:26:18,272 INFO    WriterThread:24995 [datastore.py:open_for_write():77] open: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/run-cpbj7pwj.wandb
2021-07-23 16:26:18,274 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: check_version
2021-07-23 16:26:18,274 DEBUG   SenderThread:24995 [sender.py:send():176] send: header
2021-07-23 16:26:18,275 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: check_version
2021-07-23 16:26:18,466 DEBUG   SenderThread:24995 [sender.py:send():176] send: run
2021-07-23 16:26:18,722 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: run_start
2021-07-23 16:26:18,726 INFO    SenderThread:24995 [dir_watcher.py:__init__():168] watching files in: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files
2021-07-23 16:26:18,727 DEBUG   HandlerThread:24995 [meta.py:__init__():39] meta init
2021-07-23 16:26:18,727 INFO    SenderThread:24995 [sender.py:_start_run_threads():699] run started: cpbj7pwj with start time 1627068377
2021-07-23 16:26:18,727 DEBUG   HandlerThread:24995 [meta.py:__init__():53] meta init done
2021-07-23 16:26:18,727 DEBUG   SenderThread:24995 [sender.py:send():176] send: summary
2021-07-23 16:26:18,727 DEBUG   HandlerThread:24995 [meta.py:probe():210] probe
2021-07-23 16:26:18,728 INFO    SenderThread:24995 [sender.py:_save_file():821] saving file wandb-summary.json with policy end
2021-07-23 16:26:18,737 DEBUG   HandlerThread:24995 [meta.py:_setup_git():200] setup git
2021-07-23 16:26:18,755 DEBUG   HandlerThread:24995 [meta.py:_setup_git():207] setup git done
2021-07-23 16:26:18,755 DEBUG   HandlerThread:24995 [meta.py:_save_pip():57] save pip
2021-07-23 16:26:18,756 DEBUG   HandlerThread:24995 [meta.py:_save_pip():71] save pip done
2021-07-23 16:26:18,756 DEBUG   HandlerThread:24995 [meta.py:_save_conda():78] save conda
2021-07-23 16:26:19,726 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/requirements.txt
2021-07-23 16:26:19,727 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/wandb-summary.json
2021-07-23 16:26:19,727 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/conda-environment.yaml
2021-07-23 16:26:20,740 DEBUG   HandlerThread:24995 [meta.py:_save_conda():86] save conda done
2021-07-23 16:26:20,741 DEBUG   HandlerThread:24995 [meta.py:probe():252] probe done
2021-07-23 16:26:20,747 DEBUG   SenderThread:24995 [sender.py:send():176] send: files
2021-07-23 16:26:20,747 INFO    SenderThread:24995 [sender.py:_save_file():821] saving file wandb-metadata.json with policy now
2021-07-23 16:26:20,754 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:26:20,754 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:26:21,706 INFO    Thread-11 :24995 [upload_job.py:push():133] Uploaded file /tmp/tmpayq6c5__wandb/232fkaly-wandb-metadata.json
2021-07-23 16:26:21,725 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/output.log
2021-07-23 16:26:21,725 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/wandb-metadata.json
2021-07-23 16:26:35,971 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:26:35,972 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:26:47,143 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:26:51,182 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:26:51,182 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:27:07,089 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:27:07,090 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:27:17,516 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:27:22,301 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:27:22,301 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:27:38,534 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:27:38,535 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:27:47,853 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:27:53,743 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:27:53,743 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:28:08,961 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:28:08,961 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:28:18,228 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:28:24,171 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:28:24,171 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:28:39,389 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:28:39,390 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:28:48,571 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:28:54,606 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:28:54,606 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:29:01,272 ERROR   FileStreamThread:24995 [file_stream.py:_thread_except_body():286] generic exception in filestream thread
Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 282, in _thread_except_body
    self._thread_body()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 260, in _thread_body
    self._send(ready_chunks)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 327, in _send
    retry_callback=self._api.retry_callback,
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 295, in _handle_response
    raise response
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 382, in request_with_retry
    response.raise_for_status()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/cmosquera/mixed_mask_rcnn/cpbj7pwj/file_stream
2021-07-23 16:29:09,814 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:29:09,815 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:29:18,941 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:29:25,021 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:29:25,021 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:29:40,227 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:29:40,228 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:29:49,377 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:29:55,443 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: stop_status
2021-07-23 16:29:55,443 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: stop_status
2021-07-23 16:30:02,470 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:02,470 DEBUG   SenderThread:24995 [sender.py:send():176] send: telemetry
2021-07-23 16:30:02,471 DEBUG   SenderThread:24995 [sender.py:send():176] send: exit
2021-07-23 16:30:02,471 INFO    SenderThread:24995 [sender.py:send_exit():281] handling exit code: 1
2021-07-23 16:30:02,472 INFO    SenderThread:24995 [sender.py:send_exit():289] send defer
2021-07-23 16:30:02,473 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: poll_exit
2021-07-23 16:30:02,474 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: defer
2021-07-23 16:30:02,474 INFO    HandlerThread:24995 [handler.py:handle_request_defer():138] handle defer: 0
2021-07-23 16:30:02,475 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: defer
2021-07-23 16:30:02,475 INFO    SenderThread:24995 [sender.py:send_request_defer():298] handle sender defer: 0
2021-07-23 16:30:02,475 INFO    SenderThread:24995 [sender.py:send_request_defer():336] send defer: 1
2021-07-23 16:30:02,476 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: defer
2021-07-23 16:30:02,476 INFO    HandlerThread:24995 [handler.py:handle_request_defer():138] handle defer: 1
2021-07-23 16:30:02,578 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: defer
2021-07-23 16:30:02,578 INFO    SenderThread:24995 [sender.py:send_request_defer():298] handle sender defer: 1
2021-07-23 16:30:02,578 INFO    SenderThread:24995 [sender.py:send_request_defer():336] send defer: 2
2021-07-23 16:30:02,578 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:02,579 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: poll_exit
2021-07-23 16:30:02,579 DEBUG   SenderThread:24995 [sender.py:send():176] send: stats
2021-07-23 16:30:02,580 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: defer
2021-07-23 16:30:02,581 INFO    HandlerThread:24995 [handler.py:handle_request_defer():138] handle defer: 2
2021-07-23 16:30:02,581 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: defer
2021-07-23 16:30:02,581 INFO    SenderThread:24995 [sender.py:send_request_defer():298] handle sender defer: 2
2021-07-23 16:30:02,581 INFO    SenderThread:24995 [sender.py:send_request_defer():336] send defer: 3
2021-07-23 16:30:02,582 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: defer
2021-07-23 16:30:02,582 INFO    HandlerThread:24995 [handler.py:handle_request_defer():138] handle defer: 3
2021-07-23 16:30:02,582 DEBUG   SenderThread:24995 [sender.py:send():176] send: summary
2021-07-23 16:30:02,583 INFO    SenderThread:24995 [sender.py:_save_file():821] saving file wandb-summary.json with policy end
2021-07-23 16:30:02,583 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: defer
2021-07-23 16:30:02,583 INFO    SenderThread:24995 [sender.py:send_request_defer():298] handle sender defer: 3
2021-07-23 16:30:02,583 INFO    SenderThread:24995 [sender.py:send_request_defer():336] send defer: 4
2021-07-23 16:30:02,583 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: defer
2021-07-23 16:30:02,584 INFO    HandlerThread:24995 [handler.py:handle_request_defer():138] handle defer: 4
2021-07-23 16:30:02,584 DEBUG   SenderThread:24995 [sender.py:send_request():186] send_request: defer
2021-07-23 16:30:02,584 INFO    SenderThread:24995 [sender.py:send_request_defer():298] handle sender defer: 4
2021-07-23 16:30:02,681 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:02,812 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:30:02,813 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:30:02,830 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_modified():229] file/dir modified: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/output.log
2021-07-23 16:30:02,830 INFO    Thread-8  :24995 [dir_watcher.py:_on_file_modified():229] file/dir modified: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/files/wandb-summary.json
2021-07-23 16:30:04,191 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:30:04,192 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:30:06,755 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:30:06,756 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:30:06,756 ERROR   SenderThread:24995 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2021-07-23 16:30:07,784 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:11,168 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:30:11,168 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:30:12,885 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:17,986 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:20,747 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:30:20,748 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:30:23,087 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:28,188 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:33,288 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:38,389 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:41,724 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:30:41,725 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:30:43,490 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:48,590 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:53,691 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:30:58,792 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:03,893 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:08,994 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:14,095 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:17,675 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:31:17,676 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:31:19,196 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:24,296 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:29,397 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:34,498 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:39,599 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:44,700 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:49,801 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:31:54,901 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:32:00,002 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:32:05,103 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:32:10,204 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:32:15,305 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:32:20,405 DEBUG   HandlerThread:24995 [handler.py:handle_request():121] handle_request: poll_exit
2021-07-23 16:32:20,782 WARNING MainThread:24995 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-07-23 16:32:26,990 ERROR   SenderThread:24995 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-23 16:32:26,991 ERROR   SenderThread:24995 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '320443-cpbj7pwj' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-23 16:32:27,412 INFO    HandlerThread:24995 [handler.py:finish():632] shutting down handler
2021-07-23 16:32:27,611 INFO    WriterThread:24995 [datastore.py:close():258] close: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210723_162617-cpbj7pwj/run-cpbj7pwj.wandb
2021-07-23 16:32:27,788 WARNING MainThread:24995 [internal.py:is_dead():367] Internal process exiting, parent pid 24914 disappeared
2021-07-23 16:32:27,789 ERROR   MainThread:24995 [internal.py:wandb_internal():143] Internal process shutdown.
2021-07-23 16:32:27,789 ERROR   MainThread:24995 [internal.py:wandb_internal():159] Thread SenderThread:
Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 889, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 132, in execute
    self.display_gorilla_error_if_found(res)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 149, in display_gorilla_error_if_found
    "Error while calling W&B API: {} ({})".format(err["message"], res)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/errors/term.py", line 63, in termerror
    **kwargs
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/errors/term.py", line 94, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/click/utils.py", line 298, in echo
    file.write(out)  # type: ignore
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 55, in run
    self._run()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 105, in _run
    self._process(record)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal.py", line 292, in _process
    self._sm.send(record)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 178, in send
    send_handler(record)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 188, in send_request
    send_handler(record)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 313, in send_request_defer
    self.debounce()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 235, in debounce
    self._debounce_config()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 241, in _debounce_config
    name=self._run.run_id, config=config_value_dict, **self._api_settings
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 889, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 132, in execute
    self.display_gorilla_error_if_found(res)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 149, in display_gorilla_error_if_found
    "Error while calling W&B API: {} ({})".format(err["message"], res)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/errors/term.py", line 63, in termerror
    **kwargs
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/errors/term.py", line 94, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/click/utils.py", line 298, in echo
    file.write(out)  # type: ignore
wandb.errors.CommError: [Errno 32] Broken pipe
2021-07-23 16:32:27,837 INFO    MainThread:24995 [internal.py:handle_exit():78] Internal process exited
