2021-07-01 13:24:28,908 INFO    MainThread:1744 [internal.py:wandb_internal():91] W&B internal server running at pid: 1744, started at: 2021-07-01 13:24:28.907762
2021-07-01 13:24:28,912 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: check_version
2021-07-01 13:24:28,913 INFO    WriterThread:1744 [datastore.py:open_for_write():77] open: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/run-1o2ci2cj.wandb
2021-07-01 13:24:28,918 DEBUG   SenderThread:1744 [sender.py:send():176] send: header
2021-07-01 13:24:28,918 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: check_version
2021-07-01 13:24:29,159 DEBUG   SenderThread:1744 [sender.py:send():176] send: run
2021-07-01 13:24:29,455 INFO    SenderThread:1744 [dir_watcher.py:__init__():168] watching files in: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files
2021-07-01 13:24:29,455 INFO    SenderThread:1744 [sender.py:_start_run_threads():699] run started: 1o2ci2cj with start time 1625156668
2021-07-01 13:24:29,459 DEBUG   SenderThread:1744 [sender.py:send():176] send: summary
2021-07-01 13:24:29,459 INFO    SenderThread:1744 [sender.py:_save_file():821] saving file wandb-summary.json with policy end
2021-07-01 13:24:29,462 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: run_start
2021-07-01 13:24:29,523 DEBUG   HandlerThread:1744 [meta.py:__init__():39] meta init
2021-07-01 13:24:29,523 DEBUG   HandlerThread:1744 [meta.py:__init__():53] meta init done
2021-07-01 13:24:29,523 DEBUG   HandlerThread:1744 [meta.py:probe():210] probe
2021-07-01 13:24:29,530 DEBUG   HandlerThread:1744 [meta.py:_setup_git():200] setup git
2021-07-01 13:24:29,546 DEBUG   HandlerThread:1744 [meta.py:_setup_git():207] setup git done
2021-07-01 13:24:29,547 DEBUG   HandlerThread:1744 [meta.py:_save_pip():57] save pip
2021-07-01 13:24:29,547 DEBUG   HandlerThread:1744 [meta.py:_save_pip():71] save pip done
2021-07-01 13:24:29,548 DEBUG   HandlerThread:1744 [meta.py:_save_conda():78] save conda
2021-07-01 13:24:30,461 INFO    Thread-8  :1744 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/wandb-summary.json
2021-07-01 13:24:30,462 INFO    Thread-8  :1744 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/conda-environment.yaml
2021-07-01 13:24:30,463 INFO    Thread-8  :1744 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/requirements.txt
2021-07-01 13:24:35,459 INFO    Thread-8  :1744 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/output.log
2021-07-01 13:24:44,375 DEBUG   HandlerThread:1744 [meta.py:_save_conda():86] save conda done
2021-07-01 13:24:44,375 DEBUG   HandlerThread:1744 [meta.py:probe():252] probe done
2021-07-01 13:24:44,432 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:24:44,433 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:24:44,464 INFO    Thread-8  :1744 [dir_watcher.py:_on_file_created():216] file/dir created: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/wandb-metadata.json
2021-07-01 13:24:44,658 DEBUG   SenderThread:1744 [sender.py:send():176] send: files
2021-07-01 13:24:44,662 INFO    SenderThread:1744 [sender.py:_save_file():821] saving file wandb-metadata.json with policy now
2021-07-01 13:24:44,849 ERROR   FileStreamThread:1744 [file_stream.py:_thread_except_body():286] generic exception in filestream thread
Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 282, in _thread_except_body
    self._thread_body()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 260, in _thread_body
    self._send(ready_chunks)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 327, in _send
    retry_callback=self._api.retry_callback,
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 295, in _handle_response
    raise response
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 382, in request_with_retry
    response.raise_for_status()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/cmosquera/mixed_mask_rcnn/1o2ci2cj/file_stream
2021-07-01 13:24:57,933 DEBUG   SenderThread:1744 [sender.py:send():176] send: stats
2021-07-01 13:24:59,660 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:24:59,660 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:25:14,885 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:25:14,886 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:25:28,337 DEBUG   SenderThread:1744 [sender.py:send():176] send: stats
2021-07-01 13:25:30,104 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:25:30,105 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:25:45,341 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:25:45,342 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:25:58,726 DEBUG   SenderThread:1744 [sender.py:send():176] send: stats
2021-07-01 13:26:00,558 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:26:00,559 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:26:15,776 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:26:15,776 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:26:29,153 DEBUG   SenderThread:1744 [sender.py:send():176] send: stats
2021-07-01 13:26:32,003 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:26:32,004 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:26:47,219 DEBUG   HandlerThread:1744 [handler.py:handle_request():121] handle_request: stop_status
2021-07-01 13:26:47,220 DEBUG   SenderThread:1744 [sender.py:send_request():186] send_request: stop_status
2021-07-01 13:26:52,193 WARNING MainThread:1744 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-07-01 13:26:59,544 DEBUG   SenderThread:1744 [sender.py:send():176] send: stats
2021-07-01 13:27:07,890 WARNING MainThread:1744 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-07-01 13:27:07,890 ERROR   MainThread:1744 [internal.py:wandb_internal():150] Internal process interrupted.
2021-07-01 13:27:08,545 INFO    WriterThread:1744 [datastore.py:close():258] close: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/run-1o2ci2cj.wandb
2021-07-01 13:27:08,546 INFO    SenderThread:1744 [sender.py:finish():925] shutting down sender
2021-07-01 13:27:08,546 INFO    SenderThread:1744 [dir_watcher.py:finish():282] shutting down directory watcher
2021-07-01 13:27:08,553 INFO    HandlerThread:1744 [handler.py:finish():632] shutting down handler
2021-07-01 13:27:09,494 INFO    SenderThread:1744 [dir_watcher.py:finish():312] scan: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files
2021-07-01 13:27:09,495 INFO    SenderThread:1744 [dir_watcher.py:finish():318] scan save: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/output.log output.log
2021-07-01 13:27:09,495 INFO    SenderThread:1744 [dir_watcher.py:finish():318] scan save: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/wandb-metadata.json wandb-metadata.json
2021-07-01 13:27:09,496 INFO    SenderThread:1744 [dir_watcher.py:finish():318] scan save: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/requirements.txt requirements.txt
2021-07-01 13:27:09,496 INFO    SenderThread:1744 [dir_watcher.py:finish():318] scan save: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/wandb-summary.json wandb-summary.json
2021-07-01 13:27:09,506 INFO    SenderThread:1744 [dir_watcher.py:finish():318] scan save: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/config.yaml config.yaml
2021-07-01 13:27:09,516 INFO    SenderThread:1744 [dir_watcher.py:finish():318] scan save: /home/usuariohi/Documentos/Repos/MixedMaskRCNN/wandb/run-20210701_132427-1o2ci2cj/files/conda-environment.yaml conda-environment.yaml
2021-07-01 13:27:09,517 INFO    SenderThread:1744 [file_pusher.py:finish():176] shutting down file pusher
2021-07-01 13:27:09,517 INFO    SenderThread:1744 [file_pusher.py:join():181] waiting for file pusher
2021-07-01 13:27:10,019 ERROR   SenderThread:1744 [file_stream.py:finish():358] FileStream exception
Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 282, in _thread_except_body
    self._thread_body()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 260, in _thread_body
    self._send(ready_chunks)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 327, in _send
    retry_callback=self._api.retry_callback,
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 295, in _handle_response
    raise response
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 382, in request_with_retry
    response.raise_for_status()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/cmosquera/mixed_mask_rcnn/1o2ci2cj/file_stream
2021-07-01 13:27:10,020 ERROR   MainThread:1744 [internal.py:wandb_internal():159] Thread SenderThread:
Traceback (most recent call last):
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 55, in run
    self._run()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 106, in _run
    self._finish()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/internal.py", line 295, in _finish
    self._sm.finish()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 936, in finish
    self._fs.finish(self._exit_code)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 360, in finish
    six.reraise(*self._exc_info)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 282, in _thread_except_body
    self._thread_body()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 260, in _thread_body
    self._send(ready_chunks)
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 327, in _send
    retry_callback=self._api.retry_callback,
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 295, in _handle_response
    raise response
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/wandb/sdk/internal/file_stream.py", line 382, in request_with_retry
    response.raise_for_status()
  File "/home/usuariohi/anaconda3/envs/pytorch-opacidad/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/cmosquera/mixed_mask_rcnn/1o2ci2cj/file_stream
2021-07-01 13:27:12,064 INFO    MainThread:1744 [internal.py:handle_exit():78] Internal process exited
